name: Debian/Ubuntu Package

on:
  push:
    branches: [develop, main, master]
  pull_request:
    branches: [develop, main, master]
  workflow_dispatch:  # For manual triggering
  schedule:
  - cron: "3 14 15 * *"  # 14:03 on the 15th of every month (UTC)

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build deb pkg
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        path: repoexplorer

    - name: Run script
      run: cd repoexplorer && sudo ./build-deb.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v4.2.0
      with:
        name: repoexplorer-amd64-deb
        path: repoexplorer_*
        overwrite: true
        compression-level: 0
