name: Nix Build

on:
  push:
  pull_request:
  workflow_dispatch:  # For manual triggering
  schedule:
  - cron: "3 14 15 * *"  # 14:03 on the 15th of every month (UTC)

jobs:
  build:
    strategy:
      matrix:
        compiler: [ghc90, ghc92, ghc94, ghc96, ghc98, ghc910, ghc912]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enable cachix
      uses: cachix/cachix-action@v16
      with:
        name: neil-mayhew
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: nix build --accept-flake-config .#dynamic.${{ matrix.compiler }}

    - name: Push to cachix
      run: |
        nix-store -qR --include-outputs $(nix-store -qd result) |
          grep -v '\.drv$' |
          cachix push neil-mayhew
